---
- name: change hostname
  hostname:
    name: "learning-tribes.{{client_name}}"
  become: yes

- name: change hosts file
  replace: 
    path: /etc/hosts
    regexp: '^127.0.0.1.*'
    replace: "127.0.0.1  localhost  learning-tribes.{{client_name}}"
  become: yes

# - name: add sensu apt key
#   apt_key:
#     url: https://sensu.global.ssl.fastly.net/apt/pubkey.gpg
#     state: present
#   become: yes

# - name: create sensu apt source file
#   shell: echo "deb     https://sensu.global.ssl.fastly.net/apt `lsb_release -a |grep Codename |awk '{print $2}'` main" | sudo tee /etc/apt/sources.list.d/sensu.list

# - name: install sensu package
#   apt:
#     name: sensu
#     update_cache: yes
#   become: yes

# - name: create sensu key folder
#   file:
#     path: /etc/sensu/ssl
#     state: directory
#   become: yes

# - name: create sensu key file
#   copy: 
#     src: ../files/{{item}}
#     dest: /etc/sensu/ssl/{{item}}
#     mode: 400
#   with_items: ['key.pem', 'cert.pem']
#   become: yes

# - name: create sensu configuration file
#   copy:
#     src: ../files/{{item}}
#     dest: /etc/sensu/conf.d/{{item}}
#     mode: 400
#   with_items: ['transport.json', 'rabbitmq.json']
#   become: yes

# - name: create remediation tasks
#   copy:
#     src: ../files/{{item}}
#     dest: /opt/sensu/embedded/bin/{{item}}
#     mode: 644
#   with_items: ['remediation_veda_ingest.sh', 'remediation_veda_encode.sh', 'remediation_veda_deliver.sh'] 
#   become: yes

- name: create script folder
  file:
    path: /opt/scripts
    state: directory
    mode: '0755'
    owner: ubuntu
    group: ubuntu
  become: yes

- name: create checkpoint scripts
  copy:
    src: ../files/{{item}}
    dest: /opt/scripts/{{item}}
  with_items: ['check_webpack_error.sh']
  become: yes

# - name: get public ip
#   uri:
#     url: http://169.254.169.254/latest/meta-data/public-ipv4
#     return_content: yes
#   register: get_public_ip_address

# - name: create sensu client file
#   template:
#     src: client.j2
#     dest: /etc/sensu/conf.d/client.json
#     mode: 400
#   become: yes

# - name: install sensu plugin
#   shell: /opt/sensu/bin/sensu-install -P sensu-plugins-load-checks,sensu-plugins-cpu-checks,sensu-plugins-disk-checks,sensu-plugins-network-checks,sensu-plugins-memory-checks,sensu-plugins-process-checks
#   become: yes

- name: install requirement package
  apt:
    name: sysstat
  become: yes

# - name: start sensu client
#   shell: /opt/sensu/bin/sensu-service start client fork
#   become: yes

- name: install pip boto3
  pip:
    name: boto3
  become: yes

