---
type: CheckConfig
api_version: core/v2
metadata:
  name: check_sensu_ec2_keepalive
  namespace: default
  annotations:
    fatigue_check/occurrences: '1'
    fatigue_check/interval: '3600'
    fatigue_check/allow_resolution: 'true'
spec:
  command: python /opt/scripts/check-sensu-EC2-keepalive.py
  handlers:
  - email
  - slack
  interval: 60
  timeout: 50
  publish: true
  subscriptions:
  - entity:sensu-go
---
type: CheckConfig
api_version: core/v2
metadata:
  name: check_sensugo_ec2_keepalive
  namespace: default
  annotations:
    fatigue_check/occurrences: '1'
    fatigue_check/interval: '3600'
    fatigue_check/allow_resolution: 'true'
spec:
  command: python /opt/scripts/check-sensugo-EC2-keepalive.py
  handlers:
  - email
  - slack
  interval: 60
  timeout: 50
  publish: true
  subscriptions:
  - entity:sensu-go