---
type: CheckConfig
api_version: core/v2
metadata:
  name: check_daily_uv_metrics
  namespace: default
spec:
  command: bash /opt/scripts/check_mysql_uv_number.sh
  cron: 0 1 * * *
  timeout: 360
  publish: true
  output_metric_format: graphite_plaintext
  output_metric_handlers:
  - graphite_instance
  subscriptions:
  - app