---
type: CheckConfig
api_version: core/v2
metadata:
  name: check_port_airflow_webserver
  namespace: default
  annotations:
    fatigue_check/occurrences: '1'
    fatigue_check/interval: '3600'
    fatigue_check/allow_resolution: 'true'
spec:
  command: check-ports.rb -p 8080 -t 2
  handlers:
  - email
  - slack
  interval: 60
  timeout: 30
  publish: true
  subscriptions:
  - airflow-web
  runtime_assets:
  - sensu-plugins-network-checks
  - ruby-runtime
---
type: CheckConfig
api_version: core/v2
metadata:
  name: check_process_airflow_webserver
  namespace: default
  annotations:
    fatigue_check/occurrences: '1'
    fatigue_check/interval: '3600'
    fatigue_check/allow_resolution: 'true'
spec:
  command: check-process.rb -p airflow-webserver
  handlers:
  - email
  - slack
  interval: 60
  timeout: 30
  publish: true
  subscriptions:
  - airflow-web
  runtime_assets:
  - sensu-plugins-process-checks
  - ruby-runtime
---
type: CheckConfig
api_version: core/v2
metadata:
  name: check_process_airflow_scheduler
  namespace: default
  annotations:
    fatigue_check/occurrences: '1'
    fatigue_check/interval: '3600'
    fatigue_check/allow_resolution: 'true'
spec:
  command: check-process.rb -p 'airflow scheduler'
  handlers:
  - email
  - slack
  interval: 60
  timeout: 30
  publish: true
  subscriptions:
  - airflow-server
  runtime_assets:
  - sensu-plugins-process-checks
  - ruby-runtime
---
type: CheckConfig
api_version: core/v2
metadata:
  name: check_process_airflow_flower
  namespace: default
  annotations:
    fatigue_check/occurrences: '1'
    fatigue_check/interval: '3600'
    fatigue_check/allow_resolution: 'true'
spec:
  command: check-process.rb -p flower
  handlers:
  - email
  - slack
  interval: 60
  timeout: 30
  publish: true
  subscriptions:
  - airflow-server
  runtime_assets:
  - sensu-plugins-process-checks
  - ruby-runtime
---
type: CheckConfig
api_version: core/v2
metadata:
  name: check_process_airflow_worker
  namespace: default
  annotations:
    fatigue_check/occurrences: '1'
    fatigue_check/interval: '3600'
    fatigue_check/allow_resolution: 'true'
spec:
  command: check-process.rb -p ForkPoolWorker
  handlers:
  - email
  - slack
  interval: 60
  timeout: 30
  publish: true
  subscriptions:
  - airflow-worker
  runtime_assets:
  - sensu-plugins-process-checks
  - ruby-runtime