---
type: Handler
api_version: core/v2
metadata:
  namespace: default
  name: slack_keepalive
spec:
  type: pipe
  command: sensu-slack-handler -w https://hooks.slack.com/services/
  timeout: 20
  filters:
  - is_incident
  - not_silenced
  - fatigue_check
  runtime_assets:
  - slack-handler