---
type: Handler
api_version: core/v2
metadata:
  name: remediation
  namespace: default
spec:
  type: pipe
  command: sensu-remediation-handler
  timeout: 10
  runtime_assets:
  - remediation-handler
  env_vars:
  - "SENSU_API_URL=http://127.0.0.1:8082"
  - "SENSU_API_USER=remediation-handler"
  - "SENSU_API_PASS=PW"