all:
  children:
    stage:
      children:
        st_stateful:
          hosts:
            192.168.50.192:
        st_tenant:
          hosts:
            192.168.50.219:
    production:
      children:
        us:
          children:
            us_stateful:
            client_us:
        fr:
          children:
            fr_stateful:
            client_fr:
        cn:
          children:
            cn_stateful:
            client_fr:

