---
- name: checkout edx-platform repo into {{ edxapp_code_dir }}
  git:
    dest: "{{ edxapp_code_dir }}"
    repo: "https://{{git_username}}:{{git_password}}@github.com/Learningtribes/platform.git"
    version: "{{ edx_platform_version }}"
    accept_hostkey: yes
    force: yes
  become_user: edxapp
  tags: ['never', 'deploy']

- name: migrate lt edxapp 
  command: "{{ COMMON_BIN_DIR }}/edxapp-migrate-{{ item }}"
  when: migrate_lt_db is defined and migrate_lt_db|lower == "yes" 
  with_items:
    - 'lms'
    - 'cms'
  tags: ['never', 'deploy']

- name: restart edxapp lms
  supervisorctl:
    name: lms
    supervisorctl_path: "{{ supervisor_ctl }}"
    config: "{{ supervisor_cfg }}"
    state: restarted
  tags: ['never', 'restart-lms']

- name: restart edxapp cms
  supervisorctl:
    name: cms
    supervisorctl_path: "{{ supervisor_ctl }}"
    config: "{{ supervisor_cfg }}"
    state: restarted
  tags: ['never', 'restart-cms']

- name: restart edxapp all
  supervisorctl:
    name: all
    supervisorctl_path: "{{ supervisor_ctl }}"
    config: "{{ supervisor_cfg }}"
    state: restarted
  become_user: root
  tags: ['never', 'deploy', 'restart-all']