---
- name: checkout edx-platform repo into {{ edxapp_code_dir }}
  git:
    dest: "{{ edxapp_code_dir }}"
    repo: "https://{{git_username}}:{{git_password}}@github.com/Learningtribes/platform.git"
    version: "{{ edx_platform_version }}"
    accept_hostkey: yes
    force: yes
  become_user: edxapp
  tags: ['never', 'deploy']

- name: migrate lt edxapp 
  command: "{{ COMMON_BIN_DIR }}/edxapp-migrate-{{ item }}"
  when: migrate_lt_db is defined and migrate_lt_db|lower == "yes" 
  with_items:
    - 'lms'
    - 'cms'
  tags: ['never', 'deploy']