---
- name: checkout edx-platform repo into {{ edxapp_code_dir }}
  git:
    dest: "{{ edxapp_code_dir }}"
    repo: "https://{{git_username}}:{{git_password}}@github.com/Learningtribes/platform.git"
    version: "{{ edx_platform_version }}"
    accept_hostkey: yes
    force: yes
  become_user: "{{ edxapp_user }}"
  register: edxapp_platform_checkout

- name: git clean after checking out edx-platform
  shell: cd {{ edxapp_code_dir }} && git clean -xdf
  become_user: "{{ edxapp_user }}"

- name: migrate lt edxapp 
  command: "{{ COMMON_BIN_DIR }}/edxapp-migrate-{{ item }}"
  when: migrate_lt_db is defined and migrate_lt_db|lower == "yes" 
  with_items: "{{ service_variants_enabled }}"

- name: restart edxapp
  supervisorctl:
    name: "{{ item }}"
    supervisorctl_path: "{{ supervisor_ctl }}"
    config: "{{ supervisor_cfg }}"
    state: restarted
  become_user: "{{ supervisor_service_user }}"
  with_items:
    - 'lms'
    - 'cms'

- name: restart edxapp_workers
  supervisorctl:
    name: "edxapp_worker:"
    supervisorctl_path: "{{ supervisor_ctl }}"
    config: "{{ supervisor_cfg }}"
    state: restarted
  become_user: "{{ common_web_user }}"