---
- name: checkout edx-platform repo
  git:
    dest: "{{ edxapp_code_dir }}"
    repo: "https://{{git_username}}:{{git_password}}@github.com/Learningtribes/platform.git"
    version: "{{ edx_platform_version }}"
    accept_hostkey: yes
    force: yes
  become_user: edxapp
  tags: ['never', 'deploy']

- name: return instance ID
  command: curl http://169.254.169.254/latest/meta-data/instance-id
  register: instanceid
  tags: ['never', 'deploy-production']

- name: get branch name on instance tag
  ec2_tag:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    region: "{{ lt_ec2_region }}"
    resource: "{{ instanceid.stdout }}"
    state: list
  register: ec2_tags
  tags: ['never', 'deploy-production']

- name: checkout {{ec2_tags['tags']['branch_name']}} from edx-platform repo into {{ edxapp_code_dir }}
  git:
    dest: "{{ edxapp_code_dir }}"
    repo: "https://{{git_username}}:{{git_password}}@github.com/Learningtribes/platform.git"
    version: "{{ec2_tags['tags']['branch_name']}}"
    accept_hostkey: yes
    force: yes
  become_user: edxapp
  tags: ['never', 'deploy-production']

- name: checkout master-sephora from edx-platform repo into {{ edxapp_code_dir }}
  git:
    dest: "{{ edxapp_code_dir }}"
    repo: "https://{{git_username}}:{{git_password}}@github.com/Learningtribes/platform.git"
    version: "master-sephora"
    accept_hostkey: yes
    force: yes
  become_user: edxapp
  tags: ['never', 'azure-deploy-production']

- name: checkout {{ edx_platform_commitid }} from edx-platform repo into {{ edxapp_code_dir }}
  git:
    dest: "{{ edxapp_code_dir }}"
    repo: "https://{{git_username}}:{{git_password}}@github.com/Learningtribes/platform.git"
    version: "{{edx_platform_commitid}}"
    accept_hostkey: yes
    force: yes
  become_user: edxapp
  tags: ['never', 'deploy-production-commitid']

- name: get system requirement content
  command: "cat /edx/app/edxapp/edx-platform/requirements/system/ubuntu/third-party-apt.txt"
  register: system_package_content
  ignore_errors: yes
  tags: ['never', 'deploy', 'deploy-production', 'deploy-production-commitid']

- name: install system requirement package
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ system_package_content['stdout_lines'] }}"
  become: yes
  ignore_errors: yes
  tags: ['never', 'deploy', 'deploy-production', 'deploy-production-commitid']

- name: install python requirement package
  pip:
    chdir: /edx/app/edxapp/edx-platform/requirements/edx
    requirements: third-party.txt
    virtualenv: /edx/app/edxapp/venvs/edxapp
  become_user: edxapp
  ignore_errors: yes
  tags: ['never', 'deploy', 'deploy-production', 'deploy-production-commitid']

- name: migrate lt edxapp 
  command: "{{ COMMON_BIN_DIR }}/edxapp-migrate-{{ item }}"
  when: migrate_lt_db is defined and migrate_lt_db|lower == "yes" 
  with_items:
    - 'lms'
    - 'cms'
  tags: ['never', 'deploy', 'deploy-production', 'deploy-production-commitid', 'azure-deploy-production']