---
# jenkins
#
# Provision a Jenkins worker instance.
# - When platform_worker is set, the resulting instance can run edx-platform tests

# All jenkins workers
- import_tasks: packer.yml
- import_tasks: system.yml
- import_tasks: python.yml

# only platform workers
- import_tasks: python_platform_worker.yml
  when: platform_worker is defined

# only loadtest driver workers
- import_tasks: loadtest_driver_worker.yml
  when: loadtest_driver_worker is defined

# Run appropriate tests
- import_tasks: test.yml
- import_tasks: test_platform_worker.yml
  when: platform_worker is defined
- import_tasks: test_android_worker.yml
  when: android_worker is defined
