---

STATEFUL_MYSQL_LOGIN_HOST: localhost
STATEFUL_MYSQL_LOGIN_PASSWORD: "{{ COMMON_MYSQL_ADMIN_PASS }}"
STATEFUL_MYSQL_LOGIN_USER: "{{ COMMON_MYSQL_ADMIN_USER }}"
STATEFUL_MYSQL_ALLOWED_HOST: localhost

STATEFUL_MYSQL_USER: "{{ TENANT_NAME }}_admin"
STATEFUL_MYSQL_PASS: "{{ TENANT_NAME }}_password"


mysql_setup_databases:
  - "{{ ECOMMERCE_DATABASE_NAME | default(None) }}"
  - "{{ XQUEUE_MYSQL_DB_NAME | default(None) }}"
  - "{{ EDXAPP_MYSQL_DB_NAME | default(None) }}"
  - "{{ EDXAPP_MYSQL_CSMH_DB_NAME | default(None) }}"
  - "{{ EDX_NOTES_API_MYSQL_DB_NAME | default(None) }}"
  - "{{ CREDENTIALS_DEFAULT_DB_NAME | default(None) }}"
  - "{{ DISCOVERY_DEFAULT_DB_NAME | default(None) }}"
  - "{{ JOURNALS_DEFAULT_DB_NAME | default(None) }}"
  - "{{ VEDA_WEB_FRONTEND_DEFAULT_DB_NAME | default(None) }}"

mysql_setup_database_users:
  - {
      db: "{{ ECOMMERCE_DATABASE_NAME | default(None) }}",
      user: "{{ ECOMMERCE_DATABASE_USER | default(None) }}",
      pass: "{{ ECOMMERCE_DATABASE_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ XQUEUE_MYSQL_DB_NAME | default(None) }}",
      user: "{{ XQUEUE_MYSQL_USER | default(None) }}",
      pass: "{{ XQUEUE_MYSQL_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ EDXAPP_MYSQL_DB_NAME | default(None) }}",
      user: "{{ EDXAPP_MYSQL_USER | default(None) }}",
      pass: "{{ EDXAPP_MYSQL_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ EDXAPP_MYSQL_CSMH_DB_NAME | default(None) }}",
      user: "{{ EDXAPP_MYSQL_CSMH_USER | default(None) }}",
      pass: "{{ EDXAPP_MYSQL_CSMH_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ CREDENTIALS_DEFAULT_DB_NAME | default(None) }}",
      user: "{{ CREDENTIALS_MYSQL_USER | default(None) }}",
      pass: "{{ CREDENTIALS_MYSQL_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ DISCOVERY_DEFAULT_DB_NAME | default(None) }}",
      user: "{{ DISCOVERY_MYSQL_USER | default(None) }}",
      pass: "{{ DISCOVERY_MYSQL_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ JOURNALS_DEFAULT_DB_NAME | default(None) }}",
      user: "{{ JOURNALS_MYSQL_USER | default(None) }}",
      pass: "{{ JOURNALS_MYSQL_PASSWORD | default(None) }}"
    }
  - {
      db: "{{ VEDA_WEB_FRONTEND_DEFAULT_DB_NAME | default(None) }}",
      user: "{{ VEDA_WEB_FRONTEND_MYSQL_USER | default(None) }}",
      pass: "{{ VEDA_WEB_FRONTEND_MYSQL_PASSWORD | default(None) }}"
    }
