filebeat.inputs:

- type: log
  paths:
    - /edx/var/log/supervisor/lms-stderr.log
  fields:
    logtype: lms
    loglevel: error
  fields_under_root: true
  multiline.pattern: '^\d{4}-'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /edx/var/log/supervisor/cms-stderr.log
  fields:
    logtype: cms
    loglevel: error
  fields_under_root: true
  multiline.pattern: '^\d{4}-'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /edx/var/log/supervisor/certs-stdout.log
  fields:
    logtype: certs
    loglevel: stdout
  fields_under_root: true

- type: log
  paths:
    - /edx/var/log/supervisor/certs-stderr.log
  fields:
    logtype: certs
    loglevel: stderr
  fields_under_root: true
  multiline.pattern: '^\w.*:'
  multiline.negate: true
  multiline.match: before

- type: log
  paths:
    - /edx/var/log/supervisor/xqueue-stderr.log
  fields:
    logtype: xqueue
  fields_under_root: true

- type: log
  paths:
    - /edx/var/log/supervisor/xqueue_consumer-stderr.log
  fields:
    logtype: xqueue_consumer
  fields_under_root: true
  multiline.pattern: '^\w.*:'
  multiline.negate: true
  multiline.match: before

- type: log
  paths:
    - /edx/var/log/supervisor/forum-stdout.log
  fields:
    logtype: forum
    loglevel: stdout
  fields_under_root: true
  multiline.pattern: '^W,'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /edx/var/log/supervisor/forum-stderr.log
  fields:
    logtype: forum
    loglevel: stderr
  fields_under_root: true

- type: log
  paths:
    - /edx/var/log/supervisor/lms_default_1-stderr.log
  fields:
    logtype: worker_lms_default
  fields_under_root: true
  multiline.pattern: '^\[?\d{4}-'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /edx/var/log/supervisor/lms_low_1-stderr.log
  fields:
    logtype: worker_lms_low
  fields_under_root: true
  multiline.pattern: '^\[?\d{4}-'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /edx/var/log/supervisor/lms_high_1-stderr.log
  fields:
    logtype: worker_lms_high
  fields_under_root: true
  multiline.pattern: '^\[?\d{4}-'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /edx/var/log/supervisor/lms_high_mem_1-stderr.log
  fields:
    logtype: worker_lms_high_mem
  fields_under_root: true
  multiline.pattern: '^\[?\d{4}-'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /edx/var/log/supervisor/lms_grade-stderr.log
  fields:
    logtype: worker_lms_grade
  fields_under_root: true
  multiline.pattern: '^\[?\d{4}-'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /edx/var/log/supervisor/lms_leaderboard-stderr.log
  fields:
    logtype: worker_lms_leaderboard
  fields_under_root: true
  multiline.pattern: '^\[?\d{4}-'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /edx/var/log/supervisor/lms_progress-stderr.log
  fields:
    logtype: worker_lms_progress
  fields_under_root: true
  multiline.pattern: '^\[?\d{4}-'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /edx/var/log/supervisor/cms_default_1-stderr.log
  fields:
    logtype: worker_cms_default
  fields_under_root: true
  multiline.pattern: '^\[?\d{4}-'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /edx/var/log/supervisor/cms_low_1-stderr.log
  fields:
    logtype: worker_cms_low
  fields_under_root: true
  multiline.pattern: '^\[?\d{4}-'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /edx/var/log/supervisor/cms_high_1-stderr.log
  fields:
    logtype: worker_cms_high
  fields_under_root: true
  multiline.pattern: '^\[?\d{4}-'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /edx/var/log/supervisor/veda_pipeline_worker_ingest-stdout.log
  fields:
    logtype: veda_ingest_worker
  fields_under_root: true

- type: log
  paths:
    - /edx/var/log/supervisor/veda_pipeline_worker_ingest-stderr.log
  fields:
    logtype: veda_ingest_worker
  fields_under_root: true
  multiline.pattern: '^[/T]'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /edx/var/log/supervisor/veda_encode_worker-stderr.log
  fields:
    logtype: veda_encode_worker
  fields_under_root: true
  multiline.pattern: '^[[TI]'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /edx/var/log/supervisor/veda_pipeline_worker_deliver-stderr.log
  fields:
    logtype: veda_deliver_worker
  fields_under_root: true
  multiline.pattern: '^[[/T]'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /edx/var/log/supervisor/discovery-stdout.log
  fields:
    logtype: discovery
  fields_under_root: true
  multiline.pattern: '^\d{4}-'
  multiline.negate: true
  multiline.match: after

- type: log
  paths:
    - /edx/var/log/supervisor/discovery-stderr.log
  fields:
    logtype: discovery
  fields_under_root: true

- type: log
  enabled: false
  paths:
    - /var/log/*.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false


setup.template.settings:
  index.number_of_shards: 1


output.logstash:
  hosts: ["kibana.learning-tribes.com.cn:5044"]
  ssl.certificate_authorities: ["/opt/ssl/logstash/ca.pem"]
  ssl.certificate: "/opt/ssl/logstash/beat.crt"
  ssl.key: "/opt/ssl/logstash/beat.key"


logging.level: info