---
- name: Download themes
  become_user: edxapp
  git:
    repo: "https://{{git_username}}:{{git_password}}@github.com/Learningtribes/hawthorn_inventory.git"
    dest: "/edx/app/edxapp/themes/{{item}}"
    version: "master"
    clone: no
    update: yes
    force: yes
  with_items: "{{LT_THEME}}"
  tags: ['never', 'all-theme', 'lms-theme', 'cms-theme']

- name: Compile all themes
  command: "{{ COMMON_BIN_DIR }}/edxapp-update-assets"
  tags: ['never', 'all-theme']

- name: Compile lms themes
  shell: "source /edx/app/edxapp/edxapp_env; cd /edx/app/edxapp/edx-platform; paver update_assets lms --settings=aws --themes={{item}}"
  args:
    executable: /bin/bash
  with_items: "{{LT_THEME}}"
  become_user: edxapp
  tags: ['never', 'lms-theme']

- name: Compile cms themes
  shell: "source /edx/app/edxapp/edxapp_env; cd /edx/app/edxapp/edx-platform; paver update_assets cms --settings=aws --themes={{item}}"
  args:
    executable: /bin/bash
  with_items: "{{LT_THEME}}"
  become_user: edxapp
  tags: ['never', 'cms-theme']