---
- name: Download themes
  become_user: edxapp
  git:
    repo: "https://{{git_username}}:{{git_password}}@github.com/Learningtribes/hawthorn_inventory.git"
    dest: "{{EDXAPP_COMPREHENSIVE_THEME_DIR}}/{{item}}"
    version: "master"
    clone: no
    update: yes
    force: yes
  with_items: "{{LT_THEME}}"
  tags: ['never', 'theme']