---
- name: Install xblock
  pip:
    name: "git+http://{{git_username}}:{{git_password}}@github.com/Learningtribes/{{item}}.git@hawthorn#egg={{item}}"
    virtualenv: "{{ edxapp_venv_dir }}"
    state: forcereinstall
    editable: yes
  become_user: edxapp
  with_items: "{{xblock_name}}"
  tags: ['never', 'deploy-xblock']

- name: Edflex xblock
  shell:
    executable: /bin/bash
    chdir: /edx/app/edxapp/edx-platform
    cmd: "source /edx/app/edxapp/edxapp_env && python manage lms migrate --settings=aws && python manage lms fetch_edflex_dataa --settings=aws"
  become_user: edxapp
  when: "{{xblock_name}}" == "edflex-xblock"
  tags: ['never', 'deploy-xblock']

- name: Install xblock on stage
  pip:
    name: "git+http://{{git_username}}:{{git_password}}@github.com/Learningtribes/{{item}}.git@{{branch_name}}#egg={{item}}"
    virtualenv: "{{ edxapp_venv_dir }}"
    state: forcereinstall
    editable: yes
  become_user: edxapp
  with_items: "{{xblock_name}}"
  tags: ['never', 'stage-deploy-xblock']
