---
- name: change shell cron job
  cron:
    env: yes
    name: SHELL
    job: /bin/bash
  become_user: discovery

- name: add refresh course metadata cron job
  cron:
    name: "refresh course metadata"
    minute: "*/5"
    job: "cd /edx/app/discovery/discovery/ && source ../discovery_env && python manage.py refresh_course_metadata"
  become_user: discovery

# - name: create script folder
#   file:
#     path: /edx/var/discovery/media/media/programs/banner_images
#     state: directory
#     mode: '0755'
#     owner: www-data
#     group: www-data
#   become: yes

# - name: copy discovery sql file
#   copy: 
#     src: ../files/discovery.sql
#     dest: /tmp/discovery.sql

# - name: execute discovery sql
#   shell: "mysql -u {{TENANT_MYSQL_USER}} -p{{TENANT_MYSQL_PASS}} -h {{TENANT_MYSQL_LOGIN_HOST}} -D {{DISCOVERY_DEFAULT_DB_NAME}} < /tmp/discovery.sql"
#   become: yes

- name: create discovery file for tenant
  template:
    src: discovery.j2
    dest: /edx/app/discovery/discovery/discovery.auth.json
    mode: 0644

- name: download inventory repo
  git: 
    repo: "{{inventory_git_url}}"
    dest: "{{inventory_repo_folder}}"
    version: "{{inventory_repo_branch}}"

- name: get dicovery configuration files
  command: "cp /edx/app/discovery/discovery/discovery.auth.json {{inventory_repo_folder}}/configuration_files/{{TENANT_NAME}}_tenant/discovery.auth.json"

- name: git push code
  shell: "git add -A; git commit -m 'add {{TENANT_NAME}} discovery configuration files'; git push"
  args:
    chdir: "{{inventory_repo_folder}}"

- name: remove inventory repo folder
  file:
    path: "{{inventory_repo_folder}}"
    state: absent

- name: fix migration confliction
  shell:
    executable: /bin/bash 
    chdir: /edx/app/discovery/discovery
    cmd: "source /edx/app/discovery/discovery_env && /edx/app/discovery/venvs/discovery/bin/python3 manage.py makemigrations --merge --noinput"
  become_user: discovery

- name: run discovery migration
  shell: source /edx/app/discovery/discovery_env;/edx/app/discovery/venvs/discovery/bin/python3 manage.py migrate 
  args:
    chdir: /edx/app/discovery/discovery
    executable: /bin/bash
  become_user: discovery
