---
- name: copy veda sql file
  copy: 
    src: ../files/veda.sql
    dest: /tmp/veda.sql

- name: execute veda sql
  shell: "mysql -u {{TENANT_MYSQL_USER}} -p{{TENANT_MYSQL_PASS}} -h {{TENANT_MYSQL_LOGIN_HOST}} -D {{VEDA_WEB_FRONTEND_DEFAULT_DB_NAME}} < /tmp/veda.sql"
  become: yes