---
LT_KEY_FILE: /edx/app/edxapp/.ssh/id_rsa

### hosts
CLIENT_NAME: "stage"
MAINAPP_HOST: ""
OTHERSAPP_HOST: ""
STATEFUL_HOST: ""
MYSQL_HOST: ""

migrate_db: "yes"
DEPLOY_ENVIRONMENT: "{{ CLIENT_NAME }}"

MYSQL_SETUP_LOGIN_HOST: ""
MYSQL_SETUP_LOGIN_USER: 'ltdbadmin'
MYSQL_SETUP_LOGIN_PASSWORD: ''
COMMON_OAUTH_BASE_URL: 'http://{{EDXAPP_HOST}}'


### --------------------- EDXAPP & WORKER --------------------------------------

## MAIN VARS
CMS_HOSTNAME: ''
CLUSTER_NAME: '{{ CLIENT_NAME }}'
EDXAPP_HOST: "{{ MAINAPP_HOST }}"
ENABLE_DEMO: true
edx_platform_repo: "https://{{ COMMON_GIT_MIRROR }}/Learningtribes/platform.git"
edx_platform_version: master
EDXAPP_LMS_BASE_SCHEME: http
EDXAPP_SITE_NAME: "{{MAINAPP_HOST}}"
EDXAPP_CMS_SITE_NAME: "{{MAINAPP_HOST}}"

EDXAPP_MYSQL_CSMH_USER: "edxapp_cmsh001"
EDXAPP_MONGO_USER: 'edxapp'

## REQUIRED PASSWORD AND SECRET
EDXAPP_CELERY_PASSWORD: ''
EDXAPP_COMMENTS_SERVICE_KEY: '{{ FORUM_API_KEY }}'
EDXAPP_EMAIL_HOST_PASSWORD: ''
EDXAPP_MYSQL_CSMH_PASSWORD: ''
EDXAPP_MYSQL_PASSWORD: ''
EDXAPP_MYSQL_PASSWORD_ADMIN: ''
EDXAPP_MYSQL_PASSWORD_READ_ONLY: ''
EDXAPP_MONGO_PASSWORD: ''
EDXAPP_EDXAPP_SECRET_KEY: ''
EDXAPP_PROFILE_IMAGE_SECRET_KEY:  ''
EDXAPP_AWS_ACCESS_KEY_ID: "{{AWS_ACCESS_KEY_ID}}"
EDXAPP_AWS_SECRET_ACCESS_KEY: "{{AWS_SECRET_ACCESS_KEY}}"


## nginx
EDXAPP_LMS_NGINX_PORT: '80'
NGINX_SET_X_FORWARDED_HEADERS: true

## THEMES
EDXAPP_ENABLE_COMPREHENSIVE_THEMING: yes
DEFAULT_SITE_THEME: sample
EDXAPP_COMPREHENSIVE_THEME_DIRS:
  - "{{edxapp_app_dir}}/themes"
ALL_THEMES:
  - {name: 'triboo', repo: "git@github.com:Learningtribes/triboo-theme.git", version: 'hawthorn'}
DEPLOY_THEMES: "{{ALL_THEMES|map(attribute='name')|list}}"
LT_THEMES: "{{ALL_THEMES | selectattr('name', 'in', DEPLOY_THEMES) | list}}"


## stateful link
EDXAPP_MEMCACHE: ['{{STATEFUL_HOST}}:11211']
EDXAPP_MYSQL_HOST: "{{MYSQL_HOST}}"
EDXAPP_MONGO_HOSTS:
- "{{STATEFUL_HOST}}"
EDXAPP_RABBIT_HOSTNAME: "{{STATEFUL_HOST}}"
EDXAPP_SEARCH_HOST: "{{STATEFUL_HOST}}"
EDXAPP_EMAIL_HOST: "{{STATEFUL_HOST}}"
EDXAPP_XQUEUE_URL: 'http://localhost:18040'

# ida link
EDXAPP_COMMENTS_SERVICE_URL:  'http://{{OTHERSAPP_HOST}}:18080'
EDXAPP_LMS_ANALYTICS_API_URL: 'http://localhost:18100'
EDXAPP_ECOMMERCE_PUBLIC_URL_ROOT: "http://{{OTHERSAPP_HOST}}:18130"
EDXAPP_ECOMMERCE_API_URL: "http://{{OTHERSAPP_HOST}}:18130/api/v2"
EDXAPP_COURSE_CATALOG_API_URL: "http://localhost:8008/api/v1"
EDXAPP_CREDENTIALS_INTERNAL_SERVICE_URL: "http://localhost:8005"
EDXAPP_CREDENTIALS_PUBLIC_SERVICE_URL: "http://localhost:8005"
EDXAPP_JOURNALS_URL_ROOT: "https://journals-{{ EDXAPP_LMS_BASE }}"
EDXAPP_JOURNALS_API_URL: "https://journals-{{ EDXAPP_LMS_BASE }}/api/v1/"
EDXAPP_EDXNOTES_PUBLIC_API: "http://localhost:18120/api/v1"
EDXAPP_EDXNOTES_INTERNAL_API: "http://localhost:18120/api/v1"


# features
EDXAPP_ENABLE_OAUTH2_PROVIDER: true
EDXAPP_OAUTH_ENFORCE_SECURE: false

# s3 related
EDXAPP_AWS_STORAGE_BUCKET_NAME: 'lt-{{DEPLOY_ENVIRONMENT}}-default'

EDXAPP_DJFS_BUCKET: "lt-{{DEPLOY_ENVIRONMENT}}-public"
EDXAPP_DJFS:
  type: 's3fs'
  aws_access_key_id: "{{EDXAPP_AWS_ACCESS_KEY_ID}}"
  aws_secret_access_key: "{{EDXAPP_AWS_SECRET_ACCESS_KEY}}"
  bucket: '{{EDXAPP_DJFS_BUCKET}}'
  prefix: "/xblock/"
  acl: "public-read"

EDXAPP_AWS_S3_CUSTOM_DOMAIN: null
EDXAPP_DEFAULT_FILE_STORAGE: storages.backends.s3boto.S3BotoStorage
EDXAPP_GRADE_STORAGE_TYPE: s3
EDXAPP_GRADE_BUCKET: '{{EDXAPP_AWS_STORAGE_BUCKET_NAME}}'
EDXAPP_GRADE_ROOT_PATH: '/grades/'
EDXAPP_FINANCIAL_REPORTS:
  BUCKET: '{{EDXAPP_AWS_STORAGE_BUCKET_NAME}}'
  STORAGE_TYPE: s3
  ROOT_PATH: 'financial'

EDXAPP_FILE_UPLOAD_STORAGE_PREFIX: 'submissions_attachments'

### --------------------- FORUM ------------------------------------------------
FORUM_USE_TCP: false
FORUM_MONGO_HOSTS:
  - "{{STATEFUL_HOST}}"
FORUM_ELASTICSEARCH_HOST: "{{STATEFUL_HOST}}"
rbenv_dir: "{{ forum_app_dir }}"

## PASSWORD
FORUM_MONGO_USER: "cs_comments_service"
FORUM_MONGO_PASSWORD: ''


### --------------------- VIDEO PIPELINE ---------------------------------------

## MAIN VARS
VEDA_EDX_BUCKET: "lt-{{ DEPLOY_ENVIRONMENT }}-videos"
VEDA_INTERNAL_BUCKET: "lt-{{ DEPLOY_ENVIRONMENT }}-veda"
VEDA_PIPELINE_WORKER_VERSION: hawthorn
VEDA_WEB_FRONTEND_VERSION: hawthorn

VIDEO_PIPELINE_BASE_RABBITMQ_BROKER: '{{ STATEFUL_HOST }}'
CREATE_EDXAPP_VIDEO_PIPELINE_INTEGRATION: yes
VIDEO_PIPELINE_BASE_MYSQL_HOST: "{{ MYSQL_HOST }}"
EDXAPP_VEDA_SERVICE_API_URL: "http://{{ OTHERSAPP_HOST }}:18555/api/"

## NEEDED SECRET AND PASSWORD
VEDA_CELERY_PASSWORD: ''
VIDEO_PIPELINE_BASE_RABBITMQ_PASS: ''
VIDEO_PIPELINE_BASE_MYSQL_PASSWORD: ''

VIDEO_PIPELINE_BASE_SOCIAL_AUTH_EDX_OIDC_KEY: "<veda_worker_id>"
VIDEO_PIPELINE_BASE_SOCIAL_AUTH_EDX_OIDC_SECRET: "<veda_worker_secret>"
VIDEO_PIPELINE_BASE_VAL_PASSWORD: "<veda_worker_password>"

VIDEO_PIPELINE_BASE_OAUTH_CLIENT_ID: "<veda_encoder_id>"
VIDEO_PIPELINE_BASE_OAUTH_CLIENT_SECRET: "<veda_encoder_secret>"

VIDEO_PIPELINE_BASE_VEDA_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
VIDEO_PIPELINE_BASE_VEDA_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"


## EDXAPP related VARS
EDXAPP_ENABLE_VIDEO_UPLOAD_PIPELINE: true
EDXAPP_VIDEO_UPLOAD_PIPELINE:
      BUCKET: "{{ VEDA_EDX_BUCKET }}"
      ROOT_PATH: 'ingest/'

EDXAPP_VIDEO_IMAGE_SETTINGS:
  VIDEO_IMAGE_MAX_BYTES: 2097152
  VIDEO_IMAGE_MIN_BYTES: 2048
  STORAGE_KWARGS:
    bucket: "{{ VEDA_EDX_BUCKET }}"
  DIRECTORY_PREFIX: 'video-images/'
  STORAGE_CLASS: 'storages.backends.s3boto.S3BotoStorage'

EDXAPP_VIDEO_TRANSCRIPTS_SETTINGS:
  VIDEO_IMAGE_MAX_BYTES: 2097152
  VIDEO_IMAGE_MIN_BYTES: 2048
  STORAGE_KWARGS:
    bucket: "{{ VEDA_EDX_BUCKET }}"
  DIRECTORY_PREFIX: 'video-transcripts/'
  STORAGE_CLASS: 'storages.backends.s3boto.S3BotoStorage'

## VEDA PIPELINE VARS
VIDEO_PIPELINE_BASE_EDX_S3_INGEST:
  BUCKET: "{{ EDXAPP_VIDEO_UPLOAD_PIPELINE['BUCKET'] }}"
  ROOT_PATH: "{{ EDXAPP_VIDEO_UPLOAD_PIPELINE['ROOT_PATH'] }}"
VIDEO_PIPELINE_BASE_AWS_VIDEO_IMAGES:
  BUCKET: "{{ EDXAPP_VIDEO_IMAGE_SETTINGS['STORAGE_KWARGS']['bucket'] }}"
  ROOT_PATH: "{{ EDXAPP_VIDEO_IMAGE_SETTINGS['DIRECTORY_PREFIX'] }}"
VIDEO_PIPELINE_BASE_AWS_VIDEO_TRANSCRIPTS:
  BUCKET: "{{ EDXAPP_VIDEO_TRANSCRIPTS_SETTINGS['STORAGE_KWARGS']['bucket'] }}"
  ROOT_PATH: "{{ EDXAPP_VIDEO_TRANSCRIPTS_SETTINGS['DIRECTORY_PREFIX'] }}"

VIDEO_PIPELINE_BASE_EDX_S3_ENDPOINT_BUCKET: "{{ EDXAPP_VIDEO_UPLOAD_PIPELINE['BUCKET'] }}"
# even we don't use cloudfront, this is still necessary.
VIDEO_PIPELINE_BASE_EDX_CLOUDFRONT_PREFIX: "https://{{ EDXAPP_VIDEO_UPLOAD_PIPELINE['BUCKET'] }}.s3.amazonaws.com"
VIDEO_PIPELINE_BASE_VEDA_S3_UPLOAD_BUCKET: "{{ VEDA_INTERNAL_BUCKET }}"
VIDEO_PIPELINE_BASE_VEDA_S3_HOTSTORE_BUCKET: "{{ VEDA_INTERNAL_BUCKET }}"
VIDEO_PIPELINE_BASE_VEDA_DELIVERABLE_BUCKET: "{{VEDA_INTERNAL_BUCKET}}"
VIDEO_PIPELINE_BASE_LMS_BASE_URL: "http://{{ MAINAPP_HOST }}"
VIDEO_PIPELINE_BASE_VAL_USERNAME: "veda_worker"
VIDEO_PIPELINE_BASE_OAUTH_CLIENT_NAME: "veda_encoder"
VIDEO_PIPELINE_BASE_CELERY_BROKER: "amqp://veda:{{ VIDEO_PIPELINE_BASE_RABBITMQ_PASS }}@{{ VIDEO_PIPELINE_BASE_RABBITMQ_BROKER }}:5672/"

### --------------------------- E-COMMERCE -------------------------------------

## MAIN VARS
ECOMMERCE_VERSION: "open-release/hawthorn.2"
ecommerce_create_demo_data: true

## REQUIRED PASSWORD AND SECRET
ECOMMERCE_BROKER_PASSWORD: ''
ECOMMERCE_DATABASE_PASSWORD: ''
ECOMMERCE_WORKER_BROKER_PASSWORD: ''
ECOMMERCE_SECRET_KEY: ''

## HOSTS
ECOMMERCE_DATABASE_HOST: "{{MYSQL_HOST}}"
ECOMMERCE_ECOMMERCE_URL_ROOT: 'http://{{OTHERSAPP_HOST}}:18130'
ECOMMERCE_LMS_URL_ROOT: 'http://{{MAINAPP_HOST}}'
ECOMMERCE_DISCOVERY_SERVICE_URL: 'http://localhost:8008'
ECOMMERCE_BROKER_HOST: "{{STATEFUL_HOST}}"
ECOMMERCE_MEMCACHE: ['{{STATEFUL_HOST}}:11211']
ECOMMERCE_WORKER_VERSION: "{{ECOMMERCE_VERSION}}"
ECOMMERCE_WORKER_BROKER_HOST: "{{STATEFUL_HOST}}"
ECOMMERCE_WORKER_ECOMMERCE_API_ROOT: 'http://{{OTHERSAPP_HOST}}:18130/api/v2/'




###---------------------------- OTHERS REQUIRED --------------------------------


ANALYTICS_PIPELINE_OUTPUT_DATABASE_PASSWORD: ''
ANALYTICS_SCHEDULE_MASTER_SSH_CREDENTIAL_PASSPHRASE: ''
COMMON_HTPASSWD_PASS: ''
COMMON_HTPASSWD_USER: ''
COMMON_MONGO_READ_ONLY_PASS: ''
COMMON_MYSQL_ADMIN_PASS: ''
COMMON_MYSQL_MIGRATE_PASS: ''
COMMON_MYSQL_READ_ONLY_PASS: ''
CREDENTIALS_MYSQL_PASSWORD: ''
DISCOVERY_EMAIL_HOST_PASSWORD: ''
DISCOVERY_MYSQL_PASSWORD: ''

FLOWER_BROKER_PASSWORD: ''
FORUM_API_KEY: ''
HIVE_METASTORE_DATABASE_PASSWORD: ''
INSIGHTS_DATABASE_PASSWORD: ''
INSIGHTS_EMAIL_HOST_PASSWORD: ''
JENKINS_ANALYTICS_GITHUB_CREDENTIAL_PASSPHRASE: ''
JENKINS_ANALYTICS_USER_PASSWORD_PLAIN: ''
MARIADB_CLUSTER_PASSWORD_ADMIN: ''
MONGO_ADMIN_PASSWORD: ''
mongo_admin_password: '{{ MONGO_ADMIN_PASSWORD }}'
NOTIFIER_COMMENT_SERVICE_API_KEY: '{{ FORUM_API_KEY }}'
NOTIFIER_EMAIL_PASS: ''
NOTIFIER_USER_SERVICE_HTTP_AUTH_PASS: ''
POSTFIX_QUEUE_EXTERNAL_SMTP_PASSWORD: ''
REDIS_PASSWORD: ''
SPLUNKFORWARDER_PASSWORD: ''
SPLUNK_SMTP_PASSWORD: ''
SPLUNK_SSL_PASSWORD: ''
SWIFT_LOG_SYNC_PASSWORD: ''
XQUEUE_BASIC_AUTH_PASSWORD: ''
XQUEUE_BASIC_AUTH_USER: ''
XQUEUE_MYSQL_PASSWORD: ''
XQUEUE_RABBITMQ_PASS: ''

RABBIT_ADMIN_PASSWORD: ''

# Secret keys for Django Applicatons
ANALYTICS_API_SECRET_KEY: ''
CREDENTIALS_SECRET_KEY: ''
DISCOVERY_SECRET_KEY: ''
EDX_NOTES_API_SECRET_KEY: ''
INSIGHTS_SECRET_KEY: ''
NOTIFIER_LMS_SECRET_KEY: ''

MONGO_USERS:
  - user: "{{ FORUM_MONGO_USER }}"
    password: "{{ FORUM_MONGO_PASSWORD }}"
    database: cs_comments_service
    roles: readWrite
  - user: "{{ EDXAPP_MONGO_USER }}"
    password: "{{ EDXAPP_MONGO_PASSWORD }}"
    database: edxapp
    roles: readWrite

RABBIT_USERS:
  - name: 'admin'
    password: "{{ RABBIT_ADMIN_PASSWORD }}"
  - name: 'edx'
    password: "{{ XQUEUE_RABBITMQ_PASS }}"
  - name: 'celery'
    password: "{{ EDXAPP_CELERY_PASSWORD }}"
  - name: 'veda'
    password: "{{ VEDA_CELERY_PASSWORD }}"

AWS_CREDENTIALS:
    - key: aws_access_key_id
      value: "{{AWS_ACCESS_KEY_ID}}"
    - key: aws_secret_access_key
      value: "{{AWS_SECRET_ACCESS_KEY}}"

