---
platform_vpc_name: PLATFORM VPC
platform_vpc_ip_block: 172.27.0.0/16
platform_vpc_subnet_A_name: platform subnet ONE
platform_vpc_subnet_A_ip_block: 172.27.200.0/24
platform_vpc_subnet_B_name: platform subnet TWO
platform_vpc_subnet_B_ip_block: 172.27.210.0/24
platform_security_group_app_name: PLATFORM VPC APP Security Group
platform_security_group_db_name: PLATFORM VPC DB Security Group
platform_security_group_rds_name: PLATFORM VPC RDS Security Group
default_instance_key_name: platform_key
region_instance_key_name: "{{region}}_{{default_instance_key_name}}.pem"
local_folder_store_instance_keys: /opt/instanceskey
s3_bucket_store_instance_keys: lt-instances-file
instance_ami_name: ubuntu16.04
inventory_git_url: "https://{{git_username}}:{{git_password}}@github.com/Learningtribes/hawthorn_inventory.git"
local_repo_folder: /opt/repo
inventory_repo_folder: "{{local_repo_folder}}/hawthorn_inventory"
inventory_repo_branch: master
hosts_ini_file: "{{inventory_repo_folder}}/hosts.ini"
configuration_git_url: "https://{{git_username}}:{{git_password}}@github.com/Learningtribes/configuration.git"
configuration_repo_folder: "{{local_repo_folder}}/configuration"
configuration_repo_branch: master
rds_cluster_name: platform-rds-cluster
rds_subnet_group_name: platform rds subnet group
rds_parameter_group_name: platform-parameter-group
rds_parameter_group_family: aurora-mysql5.7
rds_engine: aurora-mysql
rds_engine_version: 5.7.12
rds_master_username: "{{COMMON_MYSQL_ADMIN_USER}}"
rds_master_password: "{{COMMON_MYSQL_ADMIN_PASS}}"
rds_backup_retention_period: 20
rds_db_instance_name: platform-rds
rds_db_instance_type: db.t2.small
rds_db_read_only_instance_name: platform-rds-ro
rds_parameters_group_items:
  - parametername: character_set_client
    parametervalue: utf8
  - parametername: character_set_connection
    parametervalue: utf8
  - parametername: character_set_database
    parametervalue: utf8
  - parametername: character_set_results
    parametervalue: utf8
  - parametername: character_set_server
    parametervalue: utf8
  - parametername: collation_connection
    parametervalue: utf8_general_ci
  - parametername: collation_server
    parametervalue: utf8_general_ci
  - parametername: sql_mode
    parametervalue: STRICT_TRANS_TABLES