- name: Deploy edX Ecommerce
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_DATADOG: False
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'ecommerce'
  roles:
    - aws
    - role: nginx
    - role: swapfile
       SWAPFILE_SIZE: 4GB
    - role: ecommerce
      when: SANDBOX_ENABLE_ECOMMERCE

    - ecommerce
    - role: ecomworker
      ECOMMERCE_WORKER_BROKER_HOST: 127.0.0.1
      when: SANDBOX_ENABLE_ECOMMERCE

