---

# Example sandbox configuration
# for single server community
# installs

- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
    MYSQL_BIND_ADDRESS: "0.0.0.0"
#    EDXLOCAL_MYSQL_ALLOWED_HOST: "{{ hostvars['stateless'][0]['ansible_hostname'] }}"
    EDXLOCAL_MYSQL_ALLOWED_HOST: "ip-192-168-0-160.ec2.internal"
#    rabbitmq_ip: "{{ groups['datastores'][0] }}"
  vars_files:
    - roles/edxapp/defaults/main.yml
    - roles/forum/defaults/main.yml
    - roles/xqueue/defaults/main.yml
    - roles/ecommerce/defaults/main.yml
    - roles/ecomworker/defaults/main.yml
    - roles/analytics_api/defaults/main.yml
    - roles/edx_notes_api/defaults/main.yml
  roles:
    # This install mysql and creates users.
    - role: memcache
    - role: mongo
    - role: rabbitmq
    - role: oraclejdk
    - role: elasticsearch
    - role: edxlocal
    - role: edx_ansible
    # Optional extras
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: datadog-uninstall
      when: not COMMON_ENABLE_DATADOG
