---

# Example sandbox configuration
# for single server community
# installs

- name: bootstrap python
  hosts: all
  become: True
  gather_facts: False
  roles:
    - python


- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
    MYSQL_BIND_ADDRESS: "0.0.0.0"
#    EDXLOCAL_MYSQL_ALLOWED_HOST: "{{ hostvars['stateless'][0]['ansible_hostname'] }}"
    EDXLOCAL_MYSQL_ALLOWED_HOST: "*"
#    rabbitmq_ip: "{{ groups['datastores'][0] }}"
  vars_files:
    - roles/edxapp/defaults/main.yml
    - roles/credentials/defaults/main.yml
    - roles/journals/defaults/main.yml
    - roles/veda_web_frontend/defaults/main.yml
    - roles/video_pipeline_base/defaults/main.yml
    - roles/discovery/defaults/main.yml
    - roles/forum/defaults/main.yml
    - roles/xqueue/defaults/main.yml
    - roles/ecommerce/defaults/main.yml
    - roles/ecomworker/defaults/main.yml
    - roles/analytics_api/defaults/main.yml
    - roles/edx_notes_api/defaults/main.yml
  roles:
    # This install mysql and creates users.
    - role: memcache
    - role: mongo
    - role: rabbitmq
    - role: oraclejdk
    - role: elasticsearch

    - role: edxlocal
      when: MYSQL_SETUP_HOST == "localhost"
    - role: mysql_setup
      when: MYSQL_SETUP_HOST != "localhost"
    # Optional extras
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: datadog-uninstall
      when: not COMMON_ENABLE_DATADOG
