---

# Example sandbox configuration
# for single server community
# installs

- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - python

- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    edx_platform_version: 'master'
    # Set to false if deployed behind another proxy/load balancer.
    NGINX_SET_X_FORWARDED_HEADERS: false
    ecommerce_create_demo_data: false
    credentials_create_demo_data: false
    SANDBOX_ENABLE_DISCOVERY: false
    SANDBOX_ENABLE_ECOMMERCE: false
    SANDBOX_ENABLE_ANALYTICS_API: false
    SANDBOX_ENABLE_INSIGHTS: false
    SANDBOX_ENABLE_FORUM: false
    SANDBOX_ENABLE_NOTIFIER: true
    SANDBOX_ENABLE_XQUEUE: false
    SANDBOX_ENABLE_CERT: false
    JOURNALS_ENABLED: false
    EDXAPP_MYSQL_HOST: 'db-ip-address'
    EDXAPP_MONGO_HOSTS: 'db-ip-address'
    EDXAPP_SEARCH_HOST: 'db-ip-address'
    EDXAPP_MEMCACHE: [ 'db-ip-address:11211' ]
    EDXAPP_RABBIT_HOSTNAME: 'db-ip-address'
  roles:
    - role: nginx
      nginx_sites:
      - certs
      - forum
      - xqueue
      - insights
      nginx_default_sites:
      - ecommerce
    - role: ecommerce
      ECOMMERCE_DATABASE_HOST: 'db-ip-address'
      ECOMMERCE_BROKER_HOST: 'db-ip-address'
      ECOMMERCE_NGINX_PORT: 8002
      ECOMMERCE_MEMCACHE: [ 'db-ip-address:11211' ]
      ECOMMERCE_LMS_URL_ROOT: 'http://lms-domain-name'
      COMMON_OAUTH_BASE_URL: 'http://lms-domain-name'
      ECOMMERCE_BROKER_PASSWORD: '{{ EDXAPP_CELERY_PASSWORD }}'
      ECOMMERCE_SESSION_COOKIE_SECURE: false # use http protocol
      when: SANDBOX_ENABLE_ECOMMERCE
    - role: ecomworker
      ECOMMERCE_WORKER_BROKER_HOST: 'db-ip-address'
      ECOMMERCE_WORKER_BROKER_PASSWORD: '{{ EDXAPP_CELERY_PASSWORD }}'
      when: SANDBOX_ENABLE_ECOMMERCE
    - role: analytics_api
      ANALYTICS_API_DEFAULT_HOST: '172.31.62.57'
      ANALYTICS_API_REPORTS_HOST: '172.31.62.57'
      ANALYTICS_API_ELASTICSEARCH_LEARNERS_HOST: '172.31.62.57'
      edx_django_service_memcache: [ '172.31.62.57:11211' ]
      ANALYTICS_API_LMS_BASE_URL: 'http://172.31.62.113/'
      COMMON_OAUTH_BASE_URL: 'http://54.169.255.226'
      when: SANDBOX_ENABLE_ANALYTICS_API
    - role: insights
      INSIGHTS_LMS_BASE: 'http://172.31.62.113'
      INSIGHTS_CMS_BASE: 'http://172.31.62.113:18010'
      INSIGHTS_MEMCACHE: [ '172.31.62.57:11211' ]
      INSIGHTS_DATABASE_HOST: '172.31.62.57'
      when: SANDBOX_ENABLE_INSIGHTS
    - role: forum
      FORUM_MONGO_HOSTS: [ '172.31.62.57' ]
      FORUM_ELASTICSEARCH_HOST: '172.31.62.57'
      when: SANDBOX_ENABLE_FORUM
    - role: discovery
      DISCOVERY_MEMCACHE: [ '172.31.62.57:11211' ]
      DISCOVERY_MYSQL: '172.31.62.57'
      DISCOVERY_ELASTICSEARCH_URL: 'http://172.31.62.57:9200/'
      COMMON_OAUTH_BASE_URL: 'http://54.169.255.226'
      when: SANDBOX_ENABLE_DISCOVERY
    - role: journals
      JOURNALS_MYSQL: '172.31.62.57'
      JOURNALS_MEMCACHE: [ '172.31.62.57:11211' ]
      EDXAPP_SITE_NAME: 'localhost'
      EDXAPP_LMS_BASE: 'localhost'
      COMMON_OAUTH_BASE_URL: 'http://54.169.255.226'
      JOURNALS_ELASTICSEARCH_URL: 'http://172.31.62.57:9500'
      when: JOURNALS_ENABLED
    - role: notifier
      NOTIFIER_LMS_URL_BASE: 'http://172.31.62.113'
      NOTIFIER_USER_SERVICE_BASE: 'http://172.31.62.113'
      NOTIFIER_DIGEST_TASK_INTERVAL: 5
      when: SANDBOX_ENABLE_NOTIFIER
    - role: xqueue
      XQUEUE_MYSQL_HOST: '172.31.62.57'
      update_users: True
      when: SANDBOX_ENABLE_XQUEUE
    - role: certs
      when: SANDBOX_ENABLE_CERT
    - edx_ansible
    - postfix_queue
