---

# Example sandbox configuration
# for single server community
# installs

- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - python

- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    edx_platform_version: 'master'
    JOURNALS_ENABLED: true
  vars_files:
    - roles/common_vars/defaults/main.yml
    - roles/edxapp/defaults/main.yml  #import edxapp database name variable
    - roles/common_vars/defaults/main.yml #import common mysql database name, user name variable
    - roles/analytics_api/defaults/main.yml #import analytics database name variable
    - roles/insights/defaults/main.yml  #import insights database name variable
    - roles/ecommerce/defaults/main.yml   #import ecommerce database name variable
    - roles/xqueue/defaults/main.yml  #import xqueue database name variable
    - roles/edx_notes_api/defaults/main.yml  #import notes database name variable
    - roles/credentials/defaults/main.yml #import credentials database name variable
    - roles/discovery/defaults/main.yml #import discovery database name variable
    - roles/journals/defaults/main.yml  #import journals database name variable
    - roles/veda_web_frontend/defaults/main.yml #import veda database name variable
    - roles/video_pipeline_base/defaults/main.yml #import veda database name variable
  roles:
    - role: nginx
      EDXAPP_LMS_NGINX_PORT: '80'
      # Set to false if deployed behind another proxy/load balancer.
      NGINX_SET_X_FORWARDED_HEADERS: false
      nginx_sites:
      - cms
      - lms
      nginx_default_sites:
      - lms
    - role: edxapp
      EDXAPP_MYSQL_HOST: 'db-ip-address'
      EDXAPP_MONGO_HOSTS: 'db-ip-address'
      EDXAPP_SEARCH_HOST: 'db-ip-address'
      EDXAPP_MEMCACHE: [ 'db-ip-address' ]
      EDXAPP_RABBIT_HOSTNAME: 'db-ip-address'
      celery_worker: True
    - role: edxapp
      EDXAPP_MYSQL_HOST: 'db-ip-address'
      EDXAPP_MONGO_HOSTS: 'db-ip-address'
      EDXAPP_SEARCH_HOST: 'db-ip-address'
      EDXAPP_MEMCACHE: [ 'db-ip-address' ]
      EDXAPP_RABBIT_HOSTNAME: 'db-ip-address'
      EDXAPP_ECOMMERCE_API_URL: 'http://ecommerce-domain-name:8002/api/v2'
      EDXAPP_ECOMMERCE_PUBLIC_URL_ROOT: 'http://ecommerce-domain-name:8002'
      EDXAPP_ENABLE_OAUTH2_PROVIDER: true
      EDXAPP_LMS_ISSUER: 'http://lms-domain-name/oauth2'
      EDXAPP_OAUTH_ENFORCE_SECURE: false # oauth2 use http protocol
      EDXAPP_COMMENTS_SERVICE_URL:  'http://forum-domain-name:18080'
      EDXAPP_LMS_SITE_NAME: 'lms-domain-name'
      EDXAPP_LMS_BASE_SCHEME: 'http' # lms use http protocol
      EDXAPP_LMS_NGINX_PORT: '80'
    - oauth_client_setup
    - edx_ansible
    - postfix_queue
