---

# Example sandbox configuration
# for single server community
# installs


- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
    edx_platform_version: 'open-release/hawthorn.master'
    migrate_db: 'no'
  vars_files:
    - roles/common_vars/defaults/main.yml
  roles:
    - edxapp

