---
- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - python

# TODO: optimize edxapp to allow theme, and worker deploy in one run
# TODO: postfix_queue allow this host
- name: Deploy edxapp
  hosts: all
  become: True
  gather_facts: True
  vars:
    serial_count: 1
    CLUSTER_NAME: 'edxapp'
    ENABLE_DEMO: true
    STATEFUL_HOST: '54.255.253.199'
    EDXAPP_HOST: '54.169.92.174'
    APP_HOST: '54.169.92.174'
    migrate_db: "yes"
    EDXAPP_LMS_NGINX_PORT: '80'
    NGINX_SET_X_FORWARDED_HEADERS: true

    # stateful link
    EDXAPP_MEMCACHE: ['{{STATEFUL_HOST}}:11211']
    EDXAPP_MYSQL_HOST: "{{STATEFUL_HOST}}"
    EDXAPP_MONGO_HOSTS:
    - "{{STATEFUL_HOST}}"
    EDXAPP_RABBIT_HOSTNAME: "{{STATEFUL_HOST}}"
    EDXAPP_SEARCH_HOST: "{{STATEFUL_HOST}}"
    EDXAPP_EMAIL_HOST: "{{STATEFUL_HOST}}"
    EDXAPP_XQUEUE_URL: 'http://localhost:18040'

    # ida link
    EDXAPP_SITE_NAME: "{{STATEFUL_HOST}}"
    EDXAPP_CMS_SITE_NAME: "{{STATEFUL_HOST}}"
    EDXAPP_LMS_BASE_SCHEME: http

    EDXAPP_COMMENTS_SERVICE_URL:  'http://localhost:18080'
    EDXAPP_LMS_ANALYTICS_API_URL: 'http://localhost:18100'
    EDXAPP_ECOMMERCE_PUBLIC_URL_ROOT: "http://{{APP_HOST}}:18130"
    EDXAPP_ECOMMERCE_API_URL: "http://{{APP_HOST}}:18130/api/v2"
    EDXAPP_COURSE_CATALOG_API_URL: "http://localhost:8008/api/v1"
    EDXAPP_CREDENTIALS_INTERNAL_SERVICE_URL: "http://localhost:8005"
    EDXAPP_CREDENTIALS_PUBLIC_SERVICE_URL: "http://localhost:8005"
    EDXAPP_JOURNALS_URL_ROOT: "https://journals-{{ EDXAPP_LMS_BASE }}"
    EDXAPP_JOURNALS_API_URL: "https://journals-{{ EDXAPP_LMS_BASE }}/api/v1/"
    EDXAPP_EDXNOTES_PUBLIC_API: "http://localhost:18120/api/v1"
    EDXAPP_EDXNOTES_INTERNAL_API: "http://localhost:18120/api/v1"

    # git
    edx_platform_repo: "https://{{ COMMON_GIT_MIRROR }}/Learningtribes/platform.git"
    edx_platform_version: master

    # features
    EDXAPP_ENABLE_OAUTH2_PROVIDER: true
    EDXAPP_OAUTH_ENFORCE_SECURE: false
    COMMON_OAUTH_BASE_URL: 'http://{{EDXAPP_HOST}}'

  serial: "{{ serial_count }}"
  roles:
   - role: swapfile
     SWAPFILE_SIZE: 4GB
   - role: aws
     when: COMMON_ENABLE_AWS_ROLE
   - role: automated
     AUTOMATED_USERS: "{{ EDXAPP_AUTOMATED_USERS | default({}) }}"
   - role: nginx
     nginx_sites:
     - lms
     - cms
     nginx_default_sites: "{{ EDXAPP_NGINX_DEFAULT_SITES }}"
     nginx_extra_sites: "{{ NGINX_EDXAPP_EXTRA_SITES }}"
     nginx_extra_configs: "{{ NGINX_EDXAPP_EXTRA_CONFIGS }}"
     nginx_redirects: "{{ NGINX_EDXAPP_CUSTOM_REDIRECTS }}"
     nginx_skip_enable_sites: "{{ EDXAPP_NGINX_SKIP_ENABLE_SITES }}"
   - role: edxapp
     celery_worker: True
   - role: edxapp
   - role: demo
     when: ENABLE_DEMO is defined and ENABLE_DEMO

   - role: devstack_sqlite_fix
     when: devstack is defined and devstack
