---
- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - python

- name: Deploy edxapp
  hosts: all
  become: True
  gather_facts: True
  vars:
    serial_count: 1
  vars_files:
   - roles/lt_aws_initial/vars/main.yml
  serial: "{{ serial_count }}"
  roles:
   - role: swapfile
     SWAPFILE_SIZE: 4GB
   - role: aws
     when: COMMON_ENABLE_AWS_ROLE
   - role: automated
     AUTOMATED_USERS: "{{ EDXAPP_AUTOMATED_USERS | default({}) }}"
   - role: nginx
     nginx_sites:
     - lms
     - cms
     nginx_default_sites: "{{ EDXAPP_NGINX_DEFAULT_SITES }}"
     nginx_extra_sites: "{{ NGINX_EDXAPP_EXTRA_SITES }}"
     nginx_extra_configs: "{{ NGINX_EDXAPP_EXTRA_CONFIGS }}"
     nginx_redirects: "{{ NGINX_EDXAPP_CUSTOM_REDIRECTS }}"
     nginx_skip_enable_sites: "{{ EDXAPP_NGINX_SKIP_ENABLE_SITES }}"
   - role: elasticsearch
   - role: memcache
   - role: edxapp
     celery_worker: True
   - role: lt_themes
     tags: ['never', 'assets']
   - role: edxapp
   - role: demo
     when: ENABLE_DEMO is defined and ENABLE_DEMO
   - role: devstack_sqlite_fix
     when: devstack is defined and devstack
