---
- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - python

# TODO: postfix_queue allow this host
- name: Deploy edxapp themes
  hosts: all
  become: True
  gather_facts: True
  vars:
    serial_count: 1
    DEFAULT_SITE_THEME: sample
    EDXAPP_ENABLE_COMPREHENSIVE_THEMING: true
    EDXAPP_COMPREHENSIVE_THEME_DIRS:
      - "{{edxapp_app_dir}}/themes"
    ENABLE_LT_THEME: yes
    LT_THEMES:
      - {name: "sample", repo: "https://github.com/open-craft/edx-theme.git", version: "harvard-dcex"}
  serial: "{{ serial_count }}"
  roles:
    - role: lt_themes
    - role: edxapp
      tags:
        - assets
