- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - python

- name: Deploy forum
  hosts: all
  become: True
  gather_facts: True
  vars:
    rbenv_dir: "{{ forum_app_dir }}"
    serial_count: 1
  serial: "{{ serial_count }}"
  roles:
    - role: aws
      when: COMMON_ENABLE_AWS_ROLE
    - role: nginx
      nginx_sites:
      - forum
    - role: forum
