- name: Deploy forum
  hosts: all
  become: True
  gather_facts: True
  vars:
    serial_count: 1
    CLUSTER_NAME: 'forum'
    migrate_db: "yes"
    STATEFUL_HOST: '54.255.253.199'
    EDXAPP_HOST: '54.169.92.174'
    APP_HOST: '54.169.92.174'
  serial: "{{ serial_count }}"
  roles:
    - aws
    - role: nginx
      nginx_sites:
      - forum
    - role: forum
      FORUM_USE_TCP: false
      FORUM_MONGO_HOSTS:
      - "{{STATEFUL_HOST}}"
      FORUM_ELASTICSEARCH_HOST: "{{STATEFUL_HOST}}"

