---
- name: bootstrap python
  hosts: all
  become: True
  gather_facts: False
  roles:
    - python

- name: Configure OAuth2 clients
  hosts: all
  become: True
  gather_facts: True
  vars:
    EDXAPP_HOST: '54.169.92.174'
    APP_HOST: '54.169.92.174'
  vars_files:
    - "roles/common_vars/defaults/main.yml"
    - "roles/edxapp/defaults/main.yml"
    - "roles/ecommerce/defaults/main.yml"
#    - "roles/insights/defaults/main.yml"
#    - "roles/credentials/defaults/main.yml"
#    - "roles/discovery/defaults/main.yml"
#    - "roles/journals/defaults/main.yml"
#    - "roles/veda_web_frontend/defaults/main.yml"
  roles:
    - role: oauth_client_setup
      ECOMMERCE_ECOMMERCE_URL_ROOT: 'http://{{APP_HOST}}:18130'

