---
- hosts: all
  become: True
  gather_facts: False
  vars_files:
    - roles/lt_aws_initial/vars/main.yml
    - roles/common_vars/defaults/main.yml
    - roles/supervisor/defaults/main.yml
    - roles/edxapp/defaults/main.yml
  roles:
    - role: lt_edxapp