---

- name: bootstrap python
  hosts: all
  become: True
  gather_facts: False
  roles:
    - python

# TODO manually config mysql_bind and memcache bind, postfix mynetwork,
- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
#    MYSQL_BIND_ADDRESS: "0.0.0.0"
    MYSQL_SETUP_ALLOWED_HOST: '%'
    MYSQL_SETUP_LOGIN_HOST: ""
    MYSQL_SETUP_LOGIN_USER: ""
    MYSQL_SETUP_LOGIN_PASSWORD: ""

#    rabbitmq_ip: "{{ groups['datastores'][0] }}"
  # memcache need to bind to 0.0.0.0
  vars_files:
    - roles/edxapp/defaults/main.yml
    - roles/credentials/defaults/main.yml
    - roles/journals/defaults/main.yml
    - roles/veda_web_frontend/defaults/main.yml
    - roles/video_pipeline_base/defaults/main.yml
    - roles/discovery/defaults/main.yml
    - roles/forum/defaults/main.yml
    - roles/xqueue/defaults/main.yml
    - roles/ecommerce/defaults/main.yml
    - roles/ecomworker/defaults/main.yml
    - roles/analytics_api/defaults/main.yml
    - roles/edx_notes_api/defaults/main.yml
  roles:
    # This install mysql and creates users.
    - role: memcache
    - role: mongo
      MONGO_BIND_IP: 0.0.0.0
    - role: rabbitmq
    - role: oraclejdk
    - role: elasticsearch
    - role: mysql_setup
    - role: postfix_queue
