- name: Deploy edX Notes API
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_DATADOG: False
    ENABLE_NEWRELIC: False
  roles:
    - aws
    - role: nginx
      nginx_sites:
        - edx_notes_api
    - role: edx_notes_api
      EDX_NOTES_API_MYSQL_HOST: localhost
      EDX_NOTES_API_VERSION: master
      EDX_NOTES_API_ELASTICSEARCH_URL:
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE
    - role: datadog-uninstall
      when: not COMMON_ENABLE_DATADOG

