---

- name: bootstrap python
  hosts: all
  become: True
  gather_facts: False
  roles:
    - python


# TODO manually config mysql_bind and memcache bind, postfix mynetwork,
- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  roles:
    - role: tenant_setup
