- name: Deploy edX Video Pipeline Web Frontend
  hosts: all
  become: True
  gather_facts: True
  vars:
    #VIDEO_PIPELINE_BASE_CELERY_BROKER: "amqp://veda:{{ VIDEO_PIPELINE_BASE_RABBITMQ_PASS }}@{{ VIDEO_PIPELINE_BASE_RABBITMQ_BROKER }}:5672/"
    #VIDEO_PIPELINE_BASE_MYSQL_PASSWORD: 'password'
    #VIDEO_PIPELINE_BASE_DEFAULT_DB_NAME: 'veda'
    #VIDEO_PIPELINE_BASE_MYSQL_HOST: SET_ME_PLEASE
    #VIDEO_PIPELINE_BASE_RABBITMQ_USER: veda
    VEDA_WEB_FRONTEND_VERSION: hawthorn
  roles:
    - aws
    - role: nginx
      nginx_default_sites:
        - veda_web_frontend
    - role: veda_web_frontend
      COMMON_GIT_PATH: Learningtribes

    # TODO! Add new relic instrumentation once all the other pieces of video pipeline are in place.
