---

- assert:
    that:
      - "EDXAPP_COMPREHENSIVE_THEME_DIRS | length > 0"
      - "EDXAPP_ENABLE_COMPREHENSIVE_THEMING"
    msg: "Theme deployment requires comprehensive theming to be enabled"

- name: make sure theme dirs exists
  file:
    path: item
    owner: "{{ edxapp_user }}"
    group: "{{ common_web_group }}"
    state: directory
  with_items: "{{EDXAPP_COMPREHENSIVE_THEME_DIRS}}"


- block:
  - name: Download themes
    become_user: "{{ edxapp_user }}"
    git:
      repo: "{{ item.repo }}"
      dest: "{{ EDXAPP_COMPREHENSIVE_THEME_DIRS.0 }}/{{ item.name }}"
      version: "{{ item.version | default('master') }}"
      accept_hostkey: yes
      force: yes
      depth: 1
    with_items: "{{ LT_THEMES }}"


  - name: Get all theme dirs
    find:
      paths: '{{ EDXAPP_COMPREHENSIVE_THEME_DIRS.0 }}/'
      file_type: 'directory'
    register: theme_dirs

  - name: Adjust owner/group of downloaded themes
    file:
      dest: "{{ item.path }}"
      owner: "{{ edxapp_user }}"
      group: "{{ common_web_group }}"
      recurse: yes
    with_items: "{{ theme_dirs.files }}"
